<?php

namespace Erp\WorkorderBundle\Entity;

/**
 * WorkorderServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkorderServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
