<?php

namespace Erp\VendorBundle\Repository;

use Erp\VendorBundle\Entity\VendorEdit;
use Doctrine\ORM\Query\Expr;

/**
 * VendorCreateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorCreateRepository extends \Doctrine\ORM\EntityRepository {

    public function getVendorQuery() {
        $qb = $this->createQueryBuilder('vc')
                ->orderBy('vc.id', 'DESC')
        ;

        return $qb->getQuery();
    }

    public function getVendorList() {
        $qb = $this->createQueryBuilder('vc');
        
        $result = $qb->select('vc.id AS id')
                ->addSelect('ve.firstName AS firstName')
                ->addSelect('ve.lastName AS lastName')
                ->join('vc.vendorEdits', 've')
                ->orderBy('vc.name', 'ASC')
                ->groupBy('ve')
                ->getQuery()
                ->getArrayResult();

        $vendor_list = array();

        foreach ($result as $item) {
            $vendor_list[$item['id']] = $item['firstName'] . ' ' . $item['lastName'];
        }

        return $vendor_list;
    }

}
