<?php

namespace Erp\VendorBundle\Repository;

/**
 * VendorEditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorEditRepository extends \Doctrine\ORM\EntityRepository {

}
